os: osx
language: generic
  
install:
  - brew update && brew upgrade boost cmake python gsl hdf5
  - /usr/local/bin/python3 -m pip install -U pip wheel delocate cython
  - git clone -b v4.2 git://github.com/ecell/ecell4
  - cd ecell4 && git submodule init && git submodule update && cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3 -DNO_SHARED:BOOL=1 . && make
  - delocate-listdeps python/dist/*.whl
  - delocate-wheel python/dist/*.whl
  - delocate-listdeps python/dist/*.whl
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 python/dist/*.whl

script:
  - pwd
  - ls

deploy:
  provider: releases
  api_key:
    secure: QiNZZTpdG378vLCWGXdDsJEx1S2T9ozLlzyinABVW9wv8OCL5F0WptAEv8iACcilovtYtPAZAimbj44meQiRFItky6dR1IgY0BiSFtiZrfZ+lfPoJQpFXqaqElwJUJkfINtuD77PD8Oz//H6jLlWRwMu02yIUSjkAH/PefZQCcyTMvovB5HI6kEdEltx6Kb8og9PdGsl71Z2gsMKGxV68RqtLxtPzqWcex2fZsEuoQ9N4ohoCvVAVgH7/14YKRPDiJ5ukyI0/Q3BSHvxHZMuYU0qKkujTGo9c7yBDeKtKfaeca3CfjOqXQKnpG7ujnxBSbF/4Oodf2Y4dxKMk6hxi8ukjxaa3/Viwj1dntNTpscyY6UWLIyg69+xg2pilPU8T0Sv6tqpdtcePl8Q/iGBYBBH81C1b03IMxBHylQ/aPnhfYDCOflyQqDoAOac0Ztd1ldMiAH1w6meOlY2Q+FcAkPWml3arB7LMA96curYIYYDQvqaHuiJgJ+UO/Jub+Y7+5vJpL3BrZKCLdavej8oaGVrLomW5rrbvIGmdY9NHHFecCcvUTtBUgKgRld6XUMJlLWXylqvH2knzU9osdOYExaoVHY1F+JDlS1pUnLZUChWKMuk/bJ4KIjCbp5ISksupSoS7Lmjw37/alE894CB+vp367uPH69uzJ1+6VQrZNM=
  file_glob: true
  file: "python/dist/*.whl"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
